//
//  CreditsView.swift
//  Scoundrel
//
//  Created by David Freeman on 2/28/25.
//

import SwiftUI

struct CreditsView: View {
    @Binding var isPresented: Bool
    
    var body: some View {
        ModalView(isPresented: $isPresented) {
            ScrollView {
                Text("Credits")
                    .font(.custom("ModernAntiqua-Regular", size: 40))
                    .foregroundStyle(.white)
                    .shadow(color: .black, radius: 2, x: 0, y: 0)
                    .padding()
                
                
                Text("Created by David Freeman")
                    .font(.custom("ModernAntiqua-Regular", size: 20))
                    .foregroundStyle(.black)
                    .padding(.bottom)
                
                Text("Inspiration")
                    .font(.custom("ModernAntiqua-Regular", size: 20))
                    .foregroundStyle(.black)
                    .frame(maxWidth: .infinity, alignment: .leading)
                Text("Inspired by Scoundrel designed by Zach Gage and Kurt Bieg.")
                    .font(.custom("ModernAntiqua-Regular", size: 15))
                    .foregroundStyle(.black)
                    .padding(.bottom)
                
                Text("Assets")
                    .font(.custom("ModernAntiqua-Regular", size: 20))
                    .foregroundStyle(.black)
                    .frame(maxWidth: .infinity, alignment: .leading)
                Text("Assets were generated by ChatGPT.")
                    .font(.custom("ModernAntiqua-Regular", size: 15))
                    .foregroundStyle(.black)
                    .padding(.bottom)
                
                Text("Icons")
                    .font(.custom("ModernAntiqua-Regular", size: 20))
                    .foregroundStyle(.black)
                    .frame(maxWidth: .infinity, alignment: .leading)
                Text("Icons were generated with Genmoji.")
                    .font(.custom("ModernAntiqua-Regular", size: 15))
                    .foregroundStyle(.black)
                    .padding(.bottom)
                
                Text("Music")
                    .font(.custom("ModernAntiqua-Regular", size: 20))
                    .foregroundStyle(.black)
                    .frame(maxWidth: .infinity, alignment: .leading)
                Text("Music was generated with Suno.")
                    .font(.custom("ModernAntiqua-Regular", size: 15))
                    .foregroundStyle(.black)
                    .padding(.bottom)
                
                Text("Sound Effects")
                    .font(.custom("ModernAntiqua-Regular", size: 20))
                    .foregroundStyle(.black)
                    .frame(maxWidth: .infinity, alignment: .leading)
                Text("Sound effects were generated with Infinity SFX.")
                    .font(.custom("ModernAntiqua-Regular", size: 15))
                    .foregroundStyle(.black)
                    .padding(.bottom)
                
                Text("Fonts")
                    .font(.custom("ModernAntiqua-Regular", size: 20))
                    .foregroundStyle(.black)
                    .frame(maxWidth: .infinity, alignment: .leading)
                Text("Fonts are from Google Fonts.")
                    .font(.custom("ModernAntiqua-Regular", size: 15))
                    .foregroundStyle(.black)
                    .padding(.bottom)
            }
            .scrollIndicators(.hidden)
            .padding()
        }
    }
}


#Preview {
    struct CreditsView_Preview: View {
        @State var isPresented: Bool = true
        
        var body: some View {
            CreditsView(isPresented: $isPresented)
        }
    }
    
    return CreditsView_Preview()
}
